# 
# Copyright SecureKey Technologies Inc. All Rights Reserved. 
# 
# SPDX-License-Identifier: Apache-2.0 
# 

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: postgres
  newName: docker.io/postgres
  newTag: "13"

configMapGenerator:
- files:
  - configure_postgres.sql
  name: postgres-configure

resources:
- deployment.yml
- service.yml
