#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: oathkeeper
  newName: oryd/oathkeeper
  newTag: v0.38.15-alpine

configMapGenerator:
- files:
  - config.yml
  name: oathkeeper-config
- files:
  - access-rules.json
  name: oathkeeper-rules

resources:
- oathkeeper.yml
