#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
# Copyright Avast Software. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: issuer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issuer
  template:
    metadata:
      labels:
        app: issuer
    spec:
      volumes:
        - name: config
          configMap:
            name: issuer-profiles-mapping-config
      containers:
      - name: issuer
        envFrom:
          - configMapRef:
              name: issuer-env
          - secretRef:
              name: issuer-env-secret
        image: sandbox-issuer:latest
        imagePullPolicy: IfNotPresent
        args: ["start"]
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
        volumeMounts:
          - name: config
            mountPath: /etc/issuer/config
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
